modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="pokewing_aggregator"
version="${version}"
displayName="PokeWing Classroom Mods"
description='''Sinifin urettigi tum ogrenci modlarini tek jar'da toplayan, her publish'te guncellenen sunucu modu.'''
authors="PokeWing Classroom"

[[dependencies.pokewing_aggregator]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pokewing_aggregator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
